name: ScenariosEnganxe
version: ${project.version}
main: me.imzomi.uhcscenarios.Main
api-version: 1.16
authors: [ ImZomi ]
description: ScenariosPlugin

commands:
  scen:
    description: scen command
  scenarios:
  cobbleonly:



