name: ScenariosEnganxe
version: 1.0-SNAPSHOT
main: me.imzomi.uhcscenarios.Main
api-version: 1.16
authors: [ ImZomi ]
description: ScenariosPlugin

commands:
  scen:
    description: scen command
  scenarios:
  cobbleonly:



