name: ScenariosEnganxe
version: 1.0-SNAPSHOT
main: me.imzomi.uhcscenarios.Main
api-version: 1.16
authors: [ ImZomi ]
description: ScenariosPlugin

commands:
  links:
    description: links command
  timber:
    description: timber command
  fireless:
    description: fireless command
  nofall:
    description: nofall command
  bowless:
    description: bowless command
  bloodanvil:
    description: bloodanvil command
  blooddiamonds:
    description: blooddiamonds command
  absorptionless:
    description: absorptionless command
  coldweapons:
    description: coldweapons command
  heavypockets:
    description: heavypockets command
  bleedingsweets:
    description: bleedingsweets command
  fastgetaway:
    description: fastgetawat command
  noclean:
    description: noclean command
  bloodgold:
    description: bloodgold command
  bloodlapis:
    description: bloodlapis command
  enchanteddeath:
    description: enchanteddeath command
  switcheroo:
    description: switcheroo command
  krenzinator:
    description: krenzinator command
  swordless:
    description: swordless command
  shieldless:
    description: shieldless command
  cripple:
    description: cripple command
  cobwebless:
    description: cobwebless command
  permakill:
    description: permakill command
  cutclean:
    description: cutclean command
  vengefulspirits:
    description: venefulspirits command
  gappleroulette:
    description: gappleroulette command
  hasteyboys:
    description: hasteyboys command
  luckyleaves:
    description: luckyleaves command
  doubleores:
    description: doubleores command
  tripleores:
    description: tripleores command
  damageparanoia:
    description: damage paranoia
  ultraparanoia:
    description: ultraparanoia command
  hasteyboysplus:
    description: hasteyboysplus command
  hasteybabies:
    description: hasteybabies command
  blastmining:
    description: blastmining command
  fencehead:
    description: fencehead command
  rewardingblocks:
    description: rewardingblocks command
  diamondless:
    description: diamondless command
  goldless:
    description: goldless command
  goldenretriever:
    description: goldenretriever command
  scen:
    description: scen command
  timebomb:
    description: timebomb command
  anvilless:
    description: anvilless command
  barebones:
    description: barebones command
  bats:
    description: bats command
  battleparanoia:
    description: battleparanoia command
  betazombies:
    description: betazombies command
  biomeboost:
    description: biomeboost command
  blocked:
    description: blocked command
  bloodenchant:
    description: bloodenchant command
  cleanslate:
    description: cleanslate command
  emeraldfever:
    description: emeraldfever command



